### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>crash-handler: 1.1.0</summary>

### Features

* add the ability to set a custom logger ([d34152b](https://github.com/Financial-Times/dotcom-reliability-kit/commit/d34152b77b89269aeedb35c01c92964645679e2e))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-reliability-kit/log-error bumped from ^1.4.0 to ^1.5.0
</details>

<details><summary>log-error: 1.5.0</summary>

### Features

* add the ability to set a custom logger ([d34152b](https://github.com/Financial-Times/dotcom-reliability-kit/commit/d34152b77b89269aeedb35c01c92964645679e2e))
</details>

<details><summary>middleware-log-errors: 1.4.0</summary>

### Features

* add the ability to set a custom logger ([d34152b](https://github.com/Financial-Times/dotcom-reliability-kit/commit/d34152b77b89269aeedb35c01c92964645679e2e))

### Bug Fixes

* bump @financial-times/n-express from 26.3.3 to 26.3.4 ([4776fce](https://github.com/Financial-Times/dotcom-reliability-kit/commit/4776fcebe2b781e43d0160b580e532dd4bc7b48b))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-reliability-kit/log-error bumped from ^1.4.0 to ^1.5.0
</details>

<details><summary>@dotcom-reliability-kit/middleware-render-error-info: 1.1.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-reliability-kit/log-error bumped from ^1.4.0 to ^1.5.0
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by rowanmanning — APPROVED** [review]

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-reliability-kit/releases/tag/crash-handler-v1.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-reliability-kit/releases/tag/log-error-v1.5.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-reliability-kit/releases/tag/middleware-log-errors-v1.4.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-reliability-kit/releases/tag/middleware-render-error-info-v1.1.12 :sunflower:

**Pull request merged**
