### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>app-info: 1.2.1</summary>

### Bug Fixes

* correct manually published versions ([5a014f1](https://github.com/Financial-Times/dotcom-reliability-kit/commit/5a014f1b0b6b6ad741253d1215b630d418a196eb))
</details>

<details><summary>@dotcom-reliability-kit/crash-handler: 1.1.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-reliability-kit/log-error bumped from ^1.5.3 to ^1.5.4
</details>

<details><summary>@dotcom-reliability-kit/log-error: 1.5.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-reliability-kit/app-info bumped from ^1.2.0 to ^1.2.1
</details>

<details><summary>logger: 1.1.2</summary>

### Bug Fixes

* correct manually published versions ([5a014f1](https://github.com/Financial-Times/dotcom-reliability-kit/commit/5a014f1b0b6b6ad741253d1215b630d418a196eb))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-reliability-kit/app-info bumped from ^1.2.0 to ^1.2.1
</details>

<details><summary>@dotcom-reliability-kit/middleware-log-errors: 1.5.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-reliability-kit/log-error bumped from ^1.5.3 to ^1.5.4
</details>

<details><summary>@dotcom-reliability-kit/middleware-render-error-info: 1.1.17</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-reliability-kit/app-info bumped from ^1.2.0 to ^1.2.1
    * @dotcom-reliability-kit/log-error bumped from ^1.5.3 to ^1.5.4
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by rowanmanning — APPROVED** [review]

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-reliability-kit/releases/tag/app-info-v1.2.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-reliability-kit/releases/tag/crash-handler-v1.1.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-reliability-kit/releases/tag/log-error-v1.5.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-reliability-kit/releases/tag/logger-v1.1.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-reliability-kit/releases/tag/middleware-log-errors-v1.5.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-reliability-kit/releases/tag/middleware-render-error-info-v1.1.17 :sunflower:

**Pull request merged**
